apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: team-red-secret
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "cluster-aws-secrets-manager/team-red/secret"
          objectType: "secretsmanager"